---
title: "**Computing and Data Ethics for Cancer Informatics**"
output:
  html_document
---


## Workshop Material

In this workshop we cover:

- Fundamentals about computing hardware
- Common file sizes for biomedical research
- Fundamentals about shared computing resources
- Computing resources designed for biomedical research
- Practices to ensure your research is transparent and reproducible
- Concepts around why transparency and reproducibility are critical for ethical research

<div class = "link_button"><a href="https://docs.google.com/presentation/d/1xjJdvDOOMGQLSd6jm9sfzfjDQEWG9xEICXbJOTq8-PQ/edit?usp=sharing" target="_blank"> Slides Link</a></div>

<div class = "slido_button"><a href="https://app.sli.do/event/i9DkV4CzMwqgEvzwv7B96m" target="_blank"> Discussion Link </a></div>

<div class = "resource_button"><a 
href="https://usegalaxy.org/login/start?redirect=None" target="_blank"> Resource Link </a></div>
<br>

## Additional Resources

Computing resources for research can be found at our [computing resource table](https://jhudatascience.org/ITN_computing_resources/). 

Accompanying courses can be found here:

- [Computing course](https://jhudatascience.org/Computing_for_Cancer_Informatics/)
- [Ethical data Handling course](https://hutchdatascience.org/Ethical_Data_Handling_for_Cancer_Research/)
- [Introduction to reproducibility course](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics/introduction.html)
- [Advanced reproducibility course](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/introduction.html)

See our website for additional courses (as well as how to get a certificate for completing courses) on our [course page](https://www.itcrtraining.org/resources/courses).
