---
title: GitHub and Reproducibility Skill Sets
output:
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
css: style.css
---
```{r echo = FALSE, show = FALSE}
knitr::opts_chunk$set(number_sections = FALSE)
```
## Git-ting Started

<input type="checkbox"> Create an account or otherwise [login to GitHub](https://github.com)   
<input type="checkbox"> Install GitHub Desktop to your computer: https://desktop.github.com/download/  

## Create the repository for this activity

<input type="checkbox"> Go to the template repository for this workshop: https://github.com/fhdsl/reproducibility-sandbox

### Getting familiar with the repository

This repository is a "mock" analysis. It has an example folder and file organizational structure that looks like this:

- 00-download-data.py
- 01-heatmap.Rmd
- 01-heatmap.nb.html
- **README.md**
- renv.lock
- run_analysis.sh
- results/
- plots/
- docker/

When you look at the README for this repository however, you will notice it is blank.

### Create your own copy of this repository

<input type="checkbox"> Click the green `Use this template` button and then `Create a new repository`. If you don't see this button, you may need to expand your window.  
<input type="checkbox"> On the next screen, create a `Repository name`.   
<input type="checkbox"> Choose `Public`.  
<input type="checkbox"> Scroll to the bottom and click `Create repository`.  

## Cloning our repository

GitHub Desktop is a great tool to help use use version control and interact with GitHub.  
<input type="checkbox"> Open up GitHub Desktop on your computer.  
<input type="checkbox"> Go to `File` > `Clone Repository`.  
<input type="checkbox"> Search for your ITN workshop repository name in the tab that says `Github.com`. Click on the name of this repository in this list. You can choose where you'd like it to download on your computer underneath `Local Path`.  
<input type="checkbox"> Click the blue `Clone` button.  

### Window Juggling

Note the three buttons on the main GitHub Desktop repository page that connect us to related apps.

We will be "juggling" some windows when doing this activity:

- `Code editor` -- we'll actually edit files with this
- `Files` -- we'll find where our files are on our computer with this
- `Online GitHub` -- we will send our pull request and suggested changes to online GitHub.com with this.

## Filing a pull request

Pull requests are great for suggesting changes in a way that allow us to preview and discuss the changes before merging to the `main` version.

We will practice filing a pull request by filling in the the README. READMEs are great for getting folks up to speed on a repository or code base.

### Create a new branch

But to create a pull request, we first need to create a branch to work from that is separate from the `main` copy.

<input type="checkbox"> Click the `Current Branch` box > `New branch`.  
<input type="checkbox"> Call this new branch `readme-edit`.  

### Create an AI generated README

<input type="checkbox"> Click the `Show in Finder` button.  
<input type="checkbox"> With any text editor open up both the `01-heatmap.Rmd` file and the `README.md` file  
<input type="checkbox"> Copy all the text from `01-heatmap.Rmd` (Cmd + A)  
<input type="checkbox"> Go to phind https://www.phind.com/search  
<input type="checkbox"> Ask find to create a README from the code and paste in the code from `01-heatmap.Rmd`. You may want to do some variations on the prompt you use to ask phind to do this to get good results.   
<input type="checkbox"> Copy all the text from the desired Phind output and paste it to `README.md`. Save the file.
