---
title: Machine Learning with Galaxy
output:
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
css: style.css
---
```{r echo = FALSE, show = FALSE}
knitr::opts_chunk$set(number_sections = FALSE)
```

Note the galaxy link they should use: https://usegalaxy.org/join-training/itn-at-moffitt-2025/

## Tutorial

Train dataset: 1: Chowell_train_Response.tsv

Test dataset: 2: Chowell_test_Response.tsv

Select the target column: c22: Response

Task:
  - classification
  - Only Select Classification Models if you don't want to compare all models
    - Logistic Regression
    - Decision Tree Classifier
    - Random Forest Classifier

Customize Default Settings?
No --> Yes
Cross Validation Folds --> 2

## Other Resources

- [Full Galaxy Training Tutorial "Building the LORIS LLR6 PanCancer Model Using PyCaret"](https://training.galaxyproject.org/training-material/topics/statistics/tutorials/loris_model/tutorial.html) from which this tutorial was adapted. Changes include
  - Reducing the number of models that pycaret compares
  - Reducing the number of cross validation folds
- [A Galaxy Training Tutorial on an image classification problem](https://training.galaxyproject.org/training-material/topics/statistics/tutorials/galaxy-ludwig/tutorial.html)
- [A guide to machine learning for biologists, from nature reviews molecular cell biology](https://www-nature-com.fhcrc.idm.oclc.org/articles/s41580-021-00407-0)
- [Clinical applications of artificial intelligence and machine learning in cancer diagnosis: looking into the future, from Cancer Cell International](https://cancerci.biomedcentral.com/articles/a/s12935-021-01981-1)
- [Deep learning: new computational modelling techniques for genomics, from nature reviews genetics](https://www-nature-com.fhcrc.idm.oclc.org/articles/s41576-019-0122-6)
- [Navigating the pitfalls of applying machine learning in genomics, from nature reviews genetics](https://www-nature-com.fhcrc.idm.oclc.org/articles/s41576-021-00434-9)
