---
title: Single Cell Proteomics Activity
output:
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
css: style.css
---
```{r echo = FALSE, show = FALSE}
knitr::opts_chunk$set(number_sections = FALSE)
```

## Go to Posit Cloud 

<input type="checkbox">

## Get the data 

https://github.com/fhdsl/Moffitt_ITN_Workshop

```{r}
if (!require("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
if (!("VectraPolarisData" %in% installed.packages())) {   
  BiocManager::install("VectraPolarisData")
}

if (!("spatialTIME" %in% installed.packages())) {  
  devtools::install_github("fridleylab/spatialTIME")
}

library(VectraPolarisData)
library(spatialTIME)
```

This step will take a few minutes depending on the speed of your wifi. 
[See here for the data dictionary for this dataset](https://www.bioconductor.org/packages/release/data/experiment/vignettes/VectraPolarisData/inst/doc/VectraPolarisData.html#52_HumanOvarianCancerVP)

```{r}
spe_ovarian <- HumanOvarianCancerVP()

patient_level_df <- metadata(spe_ovarian)$clinical_data
```

```{r}
# Make sure the variable types are the same for deidentified_id and 
# deidentified_sample in their corresponding datasets
mif <- create_mif(clinical_data = example_clinical %>% 
                  mutate(deidentified_id = as.character(deidentified_id)),
                sample_data = example_summary %>% 
                  mutate(deidentified_id = as.character(deidentified_id)),
                spatial_list = example_spatial,
                patient_id = "deidentified_id", 
                sample_id = "deidentified_sample")

mif #prints a summary of how many patients, samples, and spatial files are present
```


# TODO: Just make the data clean already. 

```{r}
mnames_bad <- c("CD3..CD8.","CD3..FOXP3.","CD3..Opal.570..Positive",
                "CD8..Opal.520..Positive","FOXP3..Opal.620..Positive", 
                "PDL1..Opal.540..Positive", "PD1..Opal.650..Positive")


values =  RColorBrewer::brewer.pal(length(mnames_bad), "Accent")
names(values) = mnames_bad

#add an element in the `derived` object position
x<- plot_immunoflo(x, plot_title = "deidentified_sample",  mnames = mnames_bad,
                   cell_type = "Classifier.Label")

bad_names <- x[["derived"]][["spatial_plots"]][[4]] + 
  theme(legend.position = 'bottom') + 
  scale_color_manual(breaks = mnames_bad,
                     values = values,
                     labels = mnames_bad %>%
                       gsub("..Opal.*", "+", .) %>% 
                       gsub("\\.\\.", "+", .) %>% 
                       gsub("\\.", "+", .)) 

mnames_good <- c("CD3..Opal.570..Positive","CD8..Opal.520..Positive",
                 "FOXP3..Opal.620..Positive","PDL1..Opal.540..Positive",
                 "PD1..Opal.650..Positive","CD3..CD8.","CD3..FOXP3.")

mif <- plot_immunoflo(x, plot_title = "deidentified_sample", mnames = mnames_good, 
                    cell_type = "Classifier.Label")

good_names <- mif[["derived"]][["spatial_plots"]][[4]] + 
  theme(legend.position = 'bottom') + 
  scale_color_manual(breaks = mnames_good, 
                     values = values[match(mnames_good, names(values))],
                     labels = mnames_good %>%
                       gsub("..Opal.*", "+", .) %>% 
                       gsub("\\.\\.", "+", .) %>% 
                       gsub("\\.", "+", .))
#> Scale for colour is already present.
#> Adding another scale for colour, which will replace the existing scale.

mif$sample %>% filter(deidentified_sample == 'TMA3_[9,K].tif') %>% select(c(2, 4:15)) %>%
  pivot_longer(cols = 2:13, names_to = 'Marker', values_to = 'Count')
```


### For more learning:
